[package]
name = "grovedbg"
authors = ["Evgeny Fomin <evgeny.fomin@dash.org>"]
version = "0.2.0"
description = "GroveDB inspection tool"
edition = "2021"

[dependencies]
eframe = "0.27.2"
egui_logger = "0.4.4"
futures = "0.3.30"
grovedbg-types = { path = "../grovedb/grovedbg-types" }
hex = "0.4.3"
integer-encoding = "4.0.0"
log = "0.4.22"
reqwest = { version = "0.12.5", features = ["json"] }
slab = "0.4.9"
strum = { version = "0.26.3", features = ["strum_macros", "derive"] }
thiserror = "1.0.62"
tokio = { version = "1.38.0", features = ["rt", "sync"] }
tracing-subscriber = "0.3.18"
wasm-bindgen-futures = "0.4.42"
web-sys = "0.3.69"

[workspace]
